spring.application.name=academix
server.port=8081
spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/AcademixDB}
spring.datasource.username=${MYSQL_USERNAME:root}
spring.datasource.password=${MYSQL_PASSWORD:2612}
spring.datasource.driver-class-name=${MYSQL_DRIVER:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=update

admin.default-email=${ADMIN_EMAIL:admin@academix.com}
admin.default-password=${ADMIN_PASSWORD:2612}

app.jwt.secret=${JWT_SECRET:3sizUolKeSSA3Pz7CUi7ftyxkhCcLpfOFMAKp0qdkhM=}
app.jwt.expiration=${JWT_EXPIRATION:3600000}

spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
