package com.talha.academix.enums;

public enum ActivityAction {
    ENROLLMENT,
    PAYMENT,
    CONTENT_UPLOAD,
    EXAM_ATTEMPT,
    CERTIFICATE_AWARDED,
    TEACHING_REQUEST,

    COURSE_DRAFTED,
    COURSE_REJECTED,
    COURSE_MODIFIED,
    COURSE_APPROVED,
    COURSE_IN_DEVELOPMENT,
    COURSE_LAUNCHED,
    COURSE_DISABLED,
    COURSE_DELETION
}
